-- =============================================================================
-- AgentWatch Agent Budget Governance — Run in Supabase SQL Editor
-- =============================================================================

-- Agent budget configuration table
CREATE TABLE IF NOT EXISTS public.agent_budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  team TEXT NOT NULL,
  agent_name TEXT NOT NULL,
  monthly_budget_usd NUMERIC(12,4) NOT NULL CHECK (monthly_budget_usd > 0),
  alert_threshold_pct INTEGER NOT NULL DEFAULT 80 CHECK (alert_threshold_pct > 0 AND alert_threshold_pct <= 100),
  hard_stop BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, team, agent_name)
);

-- Index for fast agent budget lookups
CREATE INDEX IF NOT EXISTS idx_agent_budgets_lookup
  ON public.agent_budgets (tenant_id, team, agent_name);

ALTER TABLE public.agent_budgets ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON public.agent_budgets
  FOR ALL USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- RPC to upsert an agent budget
-- Parameters match callRpcWithParams call: tenant_id_param, team_param, agent_param, monthly_budget_usd, alert_threshold_pct, hard_stop
CREATE OR REPLACE FUNCTION public.upsert_agent_budget(
  tenant_id_param TEXT,
  team_param TEXT,
  agent_param TEXT,
  monthly_budget_usd NUMERIC,
  alert_threshold_pct INTEGER DEFAULT 80,
  hard_stop TEXT DEFAULT 'false'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_id BIGINT;
BEGIN
  INSERT INTO public.agent_budgets (tenant_id, team, agent_name, monthly_budget_usd, alert_threshold_pct, hard_stop, updated_at)
  VALUES (tenant_id_param, team_param, agent_param, monthly_budget_usd, alert_threshold_pct, hard_stop::boolean, NOW())
  ON CONFLICT (tenant_id, team, agent_name)
  DO UPDATE SET
    monthly_budget_usd = EXCLUDED.monthly_budget_usd,
    alert_threshold_pct = EXCLUDED.alert_threshold_pct,
    hard_stop = EXCLUDED.hard_stop,
    updated_at = NOW()
  RETURNING id INTO v_id;

  RETURN jsonb_build_object(
    'success', true,
    'id', v_id,
    'tenant_id', tenant_id_param,
    'team', team_param,
    'agent_name', agent_param,
    'monthly_budget_usd', monthly_budget_usd,
    'alert_threshold_pct', alert_threshold_pct,
    'hard_stop', hard_stop::boolean
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.upsert_agent_budget(text, text, text, numeric, integer, text) TO service_role;

-- RPC to check all agent budgets (compare current spend against limits)
-- Parameter matches callRpc: tenant_id_param
CREATE OR REPLACE FUNCTION public.check_agent_budgets(tenant_id_param TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_result JSONB;
BEGIN
  WITH agent_spend AS (
    SELECT
      ab.team,
      ab.agent_name,
      ab.monthly_budget_usd,
      ab.alert_threshold_pct,
      ab.hard_stop,
      COALESCE(SUM(l.prompt_tokens + l.completion_tokens), 0) AS total_tokens,
      COALESCE(SUM(
        ((l.prompt_tokens::NUMERIC * COALESCE(mp.prompt_cost_per_million, 1.0)) / 1000000) +
        ((l.completion_tokens::NUMERIC * COALESCE(mp.completion_cost_per_million, 1.0)) / 1000000)
      ), 0) AS current_spend_usd
    FROM public.agent_budgets ab
    LEFT JOIN public.llm_request_logs l
      ON l.tenant_id = ab.tenant_id
      AND l.team = ab.team
      AND l.request_started_at >= date_trunc('month', NOW())
    LEFT JOIN public.model_pricing mp
      ON mp.provider = l.provider
      AND mp.model_pattern = l.model
    WHERE ab.tenant_id = tenant_id_param
    GROUP BY ab.team, ab.agent_name, ab.monthly_budget_usd, ab.alert_threshold_pct, ab.hard_stop
  )
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'team', asp.team,
      'agent_name', asp.agent_name,
      'monthly_budget_usd', asp.monthly_budget_usd,
      'current_spend_usd', ROUND(asp.current_spend_usd, 6),
      'total_tokens', asp.total_tokens,
      'pct_used', CASE
        WHEN asp.monthly_budget_usd > 0
        THEN ROUND((asp.current_spend_usd / asp.monthly_budget_usd * 100)::NUMERIC, 1)
        ELSE 0
      END,
      'hard_stop', asp.hard_stop,
      'status', CASE
        WHEN asp.current_spend_usd >= asp.monthly_budget_usd THEN 'exceeded'
        WHEN asp.current_spend_usd >= (asp.monthly_budget_usd * asp.alert_threshold_pct / 100) THEN 'warning'
        ELSE 'ok'
      END
    ) ORDER BY asp.current_spend_usd DESC
  ), '[]'::jsonb)
  INTO v_result
  FROM agent_spend asp;

  RETURN v_result;
END;
$$;

GRANT EXECUTE ON FUNCTION public.check_agent_budgets(text) TO service_role;

-- RPC to delete an agent budget
-- Parameters match callRpcWithParams call: tenant_id_param, team_param, agent_param
CREATE OR REPLACE FUNCTION public.delete_agent_budget(
  tenant_id_param TEXT,
  team_param TEXT,
  agent_param TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.agent_budgets
  WHERE tenant_id = tenant_id_param
    AND team = team_param
    AND agent_name = agent_param;

  RETURN jsonb_build_object('success', true);
END;
$$;

GRANT EXECUTE ON FUNCTION public.delete_agent_budget(text, text, text) TO service_role;
