-- =============================================================================
-- AgentWatch EU AI Act Compliance — Run in Supabase SQL Editor
-- =============================================================================

-- Compliance report storage
CREATE TABLE IF NOT EXISTS public.compliance_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  report_type TEXT NOT NULL DEFAULT 'eu_ai_act',
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  report_json JSONB NOT NULL,
  report_html TEXT,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_compliance_reports_lookup
  ON public.compliance_reports (tenant_id, report_type, generated_at DESC);

ALTER TABLE public.compliance_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON public.compliance_reports
  FOR ALL USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- RPC to generate compliance report data from llm_request_logs
CREATE OR REPLACE FUNCTION public.generate_compliance_report(
  tenant_id_param text,
  days_back integer DEFAULT 30
)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH period AS (
    SELECT
      now() - (days_back || ' days')::interval AS period_start,
      now() AS period_end
  ),
  logs AS (
    SELECT *
    FROM public.llm_request_logs, period
    WHERE tenant_id = tenant_id_param
      AND request_started_at >= period.period_start
      AND request_started_at < period.period_end
  ),
  summary AS (
    SELECT
      count(*) AS total_requests,
      count(DISTINCT session_id) AS total_sessions,
      count(DISTINCT team) AS total_teams,
      count(DISTINCT provider) AS total_providers,
      count(DISTINCT model) AS total_models,
      sum(prompt_tokens + completion_tokens) AS total_tokens,
      sum(case when error IS NOT NULL then 1 else 0 end) AS error_count,
      sum(case when is_stream then 1 else 0 end) AS stream_count,
      sum(case when identified_risks != '{}'::text[] then 1 else 0 end) AS flagged_count,
      min(request_started_at) AS first_request,
      max(request_started_at) AS last_request
    FROM logs
  ),
  risk_summary AS (
    SELECT
      risk_tag,
      count(*) AS occurrences
    FROM logs
    CROSS JOIN LATERAL unnest(identified_risks) AS risk_tag
    WHERE risk_tag <> ''
    GROUP BY risk_tag
  ),
  risk_json AS (
    SELECT coalesce(
      jsonb_object_agg(risk_tag, occurrences ORDER BY risk_tag),
      '{}'::jsonb
    ) AS risk_counts
    FROM risk_summary
  ),
  provider_breakdown AS (
    SELECT
      provider,
      model,
      count(*) AS requests,
      sum(prompt_tokens + completion_tokens) AS tokens,
      sum(prompt_tokens) AS prompt_tokens,
      sum(completion_tokens) AS completion_tokens,
      avg(total_latency_ms) AS avg_latency_ms,
      sum(case when error IS NOT NULL then 1 else 0 end) AS errors
    FROM logs
    GROUP BY provider, model
  ),
  daily_volume AS (
    SELECT
      date_trunc('day', request_started_at) AS day,
      count(*) AS requests,
      sum(prompt_tokens + completion_tokens) AS tokens
    FROM logs
    GROUP BY date_trunc('day', request_started_at)
    ORDER BY day
  ),
  anomaly_events AS (
    SELECT
      session_id,
      team,
      model,
      max(iteration_index) AS max_iteration,
      count(*) AS request_count
    FROM logs
    WHERE session_id IS NOT NULL
    GROUP BY session_id, team, model
    HAVING count(*) > 50
  )
  SELECT jsonb_build_object(
    'tenant_id', tenant_id_param,
    'report_type', 'eu_ai_act',
    'period_start', (SELECT period_start FROM period),
    'period_end', (SELECT period_end FROM period),
    'generated_at', now(),
    'summary', jsonb_build_object(
      'total_requests', s.total_requests,
      'total_sessions', s.total_sessions,
      'total_teams', s.total_teams,
      'total_providers', s.total_providers,
      'total_models', s.total_models,
      'total_tokens', s.total_tokens,
      'error_count', s.error_count,
      'error_rate', case when s.total_requests > 0 then round((s.error_count::numeric / s.total_requests) * 100, 2) else 0 end,
      'stream_count', s.stream_count,
      'flagged_count', s.flagged_count,
      'first_request', s.first_request,
      'last_request', s.last_request
    ),
    'risk_events', rj.risk_counts,
    'provider_breakdown', (
      SELECT coalesce(jsonb_agg(jsonb_build_object(
        'provider', pb.provider,
        'model', pb.model,
        'requests', pb.requests,
        'tokens', pb.tokens,
        'prompt_tokens', pb.prompt_tokens,
        'completion_tokens', pb.completion_tokens,
        'avg_latency_ms', round(pb.avg_latency_ms, 1),
        'errors', pb.errors
      )), '[]'::jsonb)
      FROM provider_breakdown pb
    ),
    'daily_volume', (
      SELECT coalesce(jsonb_agg(jsonb_build_object(
        'day', dv.day,
        'requests', dv.requests,
        'tokens', dv.tokens
      )), '[]'::jsonb)
      FROM daily_volume dv
    ),
    'high_volume_sessions', (
      SELECT coalesce(jsonb_agg(jsonb_build_object(
        'session_id', ae.session_id,
        'team', ae.team,
        'model', ae.model,
        'max_iteration', ae.max_iteration,
        'request_count', ae.request_count
      )), '[]'::jsonb)
      FROM anomaly_events ae
    ),
    'compliance_status', jsonb_build_object(
      'monitoring_active', s.total_requests > 0,
      'data_retention_days', 90,
      'risk_detection_enabled', true,
      'budget_enforcement_enabled', true,
      'pii_screening_enabled', true
    )
  )
  FROM summary s, risk_json rj;
$$;

GRANT EXECUTE ON FUNCTION public.generate_compliance_report(text, integer) TO service_role;
