-- =============================================================================
-- AgentWatch Schema Hardening — Run in Supabase SQL Editor
-- =============================================================================

-- #19: Model pricing lookup table (replaces hardcoded SQL pricing)
CREATE TABLE IF NOT EXISTS public.model_pricing (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL CHECK (provider IN ('openai', 'anthropic', 'groq', 'xai', 'gemini', 'azure', 'bedrock', 'mistral', 'cohere')),
  model_pattern TEXT NOT NULL,
  prompt_cost_per_million NUMERIC(12,6) NOT NULL,
  completion_cost_per_million NUMERIC(12,6) NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (provider, model_pattern)
);

ALTER TABLE public.model_pricing ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON public.model_pricing
  FOR ALL USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

INSERT INTO public.model_pricing (provider, model_pattern, prompt_cost_per_million, completion_cost_per_million) VALUES
  -- OpenAI
  ('openai',    'o1-preview%',          15.000000, 60.000000),
  ('openai',    'o1-mini%',             3.000000,  12.000000),
  ('openai',    'gpt-5.5-pro%',         10.000000, 30.000000),
  ('openai',    'gpt-5.5%',             5.000000,  15.000000),
  ('openai',    'gpt-5.4-mini%',        0.150000,   0.600000),
  ('openai',    'gpt-4o-mini%',         0.150000,   0.600000),
  ('openai',    'gpt-4o%',              2.500000,  10.000000),
  ('openai',    'gpt-4-turbo%',         10.000000, 30.000000),
  ('openai',    'gpt-4%',               30.000000, 60.000000),
  ('openai',    'gpt-3.5-turbo%',       0.500000,   1.500000),
  
  -- Anthropic
  ('anthropic', 'claude-fable-5%',      10.000000, 50.000000),
  ('anthropic', 'claude-mythos-5%',     10.000000, 50.000000),
  ('anthropic', 'claude-sonnet-4.6%',   3.000000,  15.000000),
  ('anthropic', 'claude-opus-4.0%',     15.000000, 75.000000),
  ('anthropic', 'claude-3-5-sonnet%',   3.000000,  15.000000),
  ('anthropic', 'claude-3-5-haiku%',    0.800000,   4.000000),
  ('anthropic', 'claude-3-opus%',       15.000000, 75.000000),
  ('anthropic', 'claude-3-sonnet%',     3.000000,  15.000000),
  ('anthropic', 'claude-3-haiku%',      0.250000,   1.250000),
  
  -- Google Gemini
  ('gemini',    'gemini-3.1-pro%',      2.000000,  12.000000),
  ('gemini',    'gemini-2.5-pro%',      1.250000,  10.000000),
  ('gemini',    'gemini-2.5-flash%',    0.300000,   2.500000),
  ('gemini',    'gemini-2.0-flash%',    0.100000,   0.400000),
  ('gemini',    'gemini-1.5-pro%',      1.250000,   5.000000),
  ('gemini',    'gemini-1.5-flash-8b%', 0.037500,   0.150000),
  ('gemini',    'gemini-1.5-flash%',    0.075000,   0.300000),
  ('gemini',    'gemini-1.0-pro%',      0.500000,   1.500000),
  
  -- xAI
  ('xai',       'grok-beta%',           5.000000,  15.000000),
  ('xai',       'grok-2%',              5.000000,  15.000000),
  ('xai',       'grok-2-mini%',         2.000000,   5.000000),
  
  -- Groq
  ('groq',      'llama3-8b%',           0.050000,   0.080000),
  ('groq',      'llama3-70b%',          0.590000,   0.790000),
  ('groq',      'llama-3.1-8b%',        0.050000,   0.080000),
  ('groq',      'llama-3.1-70b%',       0.590000,   0.790000),
  ('groq',      'llama-3.2-1b%',        0.040000,   0.040000),
  ('groq',      'llama-3.2-3b%',        0.060000,   0.060000),
  ('groq',      'mixtral-8x7b%',        0.240000,   0.240000),
  ('groq',      'gemma-2-9b%',          0.200000,   0.200000),
  
  -- Mistral
  ('mistral',   'mistral-large%',       2.000000,   6.000000),
  ('mistral',   'mistral-nemo%',        0.150000,   0.150000),
  ('mistral',   'mistral-small%',       0.200000,   0.600000),
  ('mistral',   'open-mixtral-8x22b%',  2.000000,   6.000000),
  
  -- Cohere
  ('cohere',    'command-r-plus%',      3.000000,  15.000000),
  ('cohere',    'command-r%',           0.500000,   1.500000)
  
ON CONFLICT (provider, model_pattern) DO UPDATE SET
  prompt_cost_per_million = EXCLUDED.prompt_cost_per_million,
  completion_cost_per_million = EXCLUDED.completion_cost_per_million,
  updated_at = NOW();

-- #14: Cron report dispatch idempotency table
CREATE TABLE IF NOT EXISTS public.report_dispatches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dedup_key TEXT NOT NULL UNIQUE,
  dispatched_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.report_dispatches ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON public.report_dispatches
  FOR ALL USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- #20: RLS documentation — llm_request_logs
-- RLS is enabled intentionally. Only the service_role key (used by the Edge Proxy)
-- can read/write to this table. No RLS policies are defined because all access
-- goes through the Cloudflare Worker which authenticates tenants at the application layer.
COMMENT ON TABLE public.llm_request_logs IS
  'Telemetry logs from AgentWatch edge proxy. RLS enabled; access restricted to service_role only. Tenant isolation enforced at the application layer.';

-- #21: Data retention policy — auto-purge logs older than 90 days
CREATE OR REPLACE FUNCTION public.purge_old_logs()
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  DELETE FROM public.llm_request_logs
  WHERE created_at < NOW() - INTERVAL '90 days';
$$;

-- Schedule via pg_cron (if available) or call manually:
-- SELECT cron.schedule('purge-old-logs', '0 3 * * *', 'SELECT public.purge_old_logs()');

GRANT EXECUTE ON FUNCTION public.purge_old_logs() TO service_role;
