-- =============================================================================
-- AgentWatch Team Budget Governance — Run in Supabase SQL Editor
-- =============================================================================

-- Team budget configuration table
CREATE TABLE IF NOT EXISTS public.team_budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  team TEXT NOT NULL,
  monthly_budget_usd NUMERIC(12,4) NOT NULL CHECK (monthly_budget_usd > 0),
  alert_threshold_pct INTEGER NOT NULL DEFAULT 80 CHECK (alert_threshold_pct > 0 AND alert_threshold_pct <= 100),
  hard_stop BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, team)
);

-- Index for fast team budget lookups
CREATE INDEX IF NOT EXISTS idx_team_budgets_lookup
  ON public.team_budgets (tenant_id, team);

ALTER TABLE public.team_budgets ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON public.team_budgets
  FOR ALL USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- Team spend tracking view (current month)
CREATE OR REPLACE FUNCTION public.get_team_monthly_spend(
  tenant_id_param text,
  team_param text
)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  with team_logs as (
    select
      l.provider,
      l.model,
      l.prompt_tokens,
      l.completion_tokens
    from public.llm_request_logs l
    where l.tenant_id = tenant_id_param
      and l.team = team_param
      and l.request_started_at >= date_trunc('month', now())
  ),
  priced_logs as (
    select
      tl.prompt_tokens,
      tl.completion_tokens,
      tl.prompt_tokens + tl.completion_tokens as total_tokens,
      coalesce(mp.prompt_cost_per_million, 1.00) as p_cost,
      coalesce(mp.completion_cost_per_million, 1.00) as c_cost
    from team_logs tl
    left join public.model_pricing mp 
      on tl.provider = mp.provider 
      and tl.model ilike mp.model_pattern
  ),
  aggregated as (
    select
      sum(total_tokens) as total_tokens,
      sum(
        ((prompt_tokens::numeric) * p_cost / 1000000) + 
        ((completion_tokens::numeric) * c_cost / 1000000)
      ) as estimated_cost_usd
    from priced_logs
  )
  select jsonb_build_object(
    'tenant_id', tenant_id_param,
    'team', team_param,
    'total_tokens', coalesce(a.total_tokens, 0),
    'estimated_cost_usd', round(coalesce(a.estimated_cost_usd, 0), 6),
    'period_start', date_trunc('month', now())
  )
  from aggregated a;
$$;

grant execute on function public.get_team_monthly_spend(text, text) to service_role;

-- Check all teams against budgets (for cron job)
CREATE OR REPLACE FUNCTION public.check_team_budgets(tenant_id_param text)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  with team_spend as (
    select
      tb.team,
      tb.monthly_budget_usd,
      tb.alert_threshold_pct,
      tb.hard_stop,
      coalesce(
        (public.get_team_monthly_spend(tenant_id_param, tb.team)->>'estimated_cost_usd')::numeric,
        0
      ) as current_spend
    from public.team_budgets tb
    where tb.tenant_id = tenant_id_param
  ),
  alerts as (
    select
      ts.team,
      ts.monthly_budget_usd,
      ts.current_spend,
      ts.hard_stop,
      round((ts.current_spend / ts.monthly_budget_usd * 100), 1) as pct_used,
      case
        when ts.current_spend >= ts.monthly_budget_usd then 'exceeded'
        when ts.current_spend >= (ts.monthly_budget_usd * ts.alert_threshold_pct / 100) then 'warning'
        else 'ok'
      end as status
    from team_spend ts
  )
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'team', a.team,
      'monthly_budget_usd', a.monthly_budget_usd,
      'current_spend', a.current_spend,
      'pct_used', a.pct_used,
      'hard_stop', a.hard_stop,
      'status', a.status
    ) order by a.pct_used desc
  ), '[]'::jsonb)
  from alerts a;
$$;

grant execute on function public.check_team_budgets(text) to service_role;

-- RPC to upsert a team budget
CREATE OR REPLACE FUNCTION public.upsert_team_budget(
  p_tenant_id TEXT,
  p_team TEXT,
  p_monthly_budget_usd NUMERIC,
  p_alert_threshold_pct INTEGER DEFAULT 80,
  p_hard_stop BOOLEAN DEFAULT false
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_id BIGINT;
BEGIN
  INSERT INTO public.team_budgets (tenant_id, team, monthly_budget_usd, alert_threshold_pct, hard_stop, updated_at)
  VALUES (p_tenant_id, p_team, p_monthly_budget_usd, p_alert_threshold_pct, p_hard_stop, NOW())
  ON CONFLICT (tenant_id, team)
  DO UPDATE SET
    monthly_budget_usd = EXCLUDED.monthly_budget_usd,
    alert_threshold_pct = EXCLUDED.alert_threshold_pct,
    hard_stop = EXCLUDED.hard_stop,
    updated_at = NOW()
  RETURNING id INTO v_id;

  RETURN jsonb_build_object('success', true, 'id', v_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.upsert_team_budget(text, text, numeric, integer, boolean) TO service_role;