-- =============================================================================
-- AgentWatch Custom Anomaly Rules — Run in Supabase SQL Editor
-- =============================================================================

-- Tenant policy rules stored as JSONB for flexible schema
CREATE TABLE IF NOT EXISTS public.tenant_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL,
  name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  priority INTEGER NOT NULL DEFAULT 100,
  "condition" JSONB NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('allow', 'block', 'throttle', 'alert', 'tag')),
  action_config JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tenant_rules_lookup
  ON public.tenant_rules (tenant_id, enabled, priority DESC);

ALTER TABLE public.tenant_rules ENABLE ROW LEVEL SECURITY;

CREATE POLICY service_role_only ON public.tenant_rules
  FOR ALL USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

COMMENT ON TABLE public.tenant_rules IS
  'Per-tenant custom anomaly/policy rules. Condition is JSONB with fields: model, model_pattern, provider, team, project, prompt_tokens_min/max, completion_tokens_min/max, total_tokens_min/max, hour_min/hour_max, day_of_week. Actions: allow, block, throttle, alert, tag.';

-- RPC to fetch active rules for a tenant (ordered by priority descending)
CREATE OR REPLACE FUNCTION public.get_tenant_rules(tenant_id_param text)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT COALESCE(
    JSONB_AGG(
      JSONB_BUILD_OBJECT(
        'id', r.id,
        'name', r.name,
        'enabled', r.enabled,
        'priority', r.priority,
        'condition', r."condition",
        'action', r.action,
        'action_config', r.action_config
      ) ORDER BY r.priority DESC
    ),
    '[]'::jsonb
  )
  FROM public.tenant_rules r
  WHERE r.tenant_id = tenant_id_param
    AND r.enabled = true;
$$;

GRANT EXECUTE ON FUNCTION public.get_tenant_rules(text) TO service_role;
